restart_file: .na
start_datetime: 2021-01-01 00:00:00
end_datetime: .na
forecast_start_datetime: 2021-12-31 00:00:00
forecast_horizon: 0.0
sim_name: ltreb_free
configure_flare: configure_flare_glm_aed.yml
configure_obs: observation_processing.yml
use_s3: no
