on:
  workflow_dispatch:
  schedule:
  - cron: "0 11 * * *"

jobs:
  run_GOTM:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run GOTM forecast with DA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:   Rscript $GITHUB_WORKSPACE/workflows/ler/combined_workflow_GOTM.R TRUE

  run_GOTM_noDA:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run GOTM forecast without DA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:   Rscript $GITHUB_WORKSPACE/workflows/ler/combined_workflow_GOTM.R FALSE

  run_Simstrat:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Simstrat forecast with DA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:   Rscript $GITHUB_WORKSPACE/workflows/ler/combined_workflow_Simstrat.R TRUE

  run_Simstrat_noDA:
    runs-on: ubuntu-latest
    container:
      image: rqthomas/flare-rocker:4.2.1
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run Simstrat forecast without DA
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:   Rscript $GITHUB_WORKSPACE/workflows/ler/combined_workflow_Simstrat.R FALSE
